name: Create package
on: 
  push:
    tags:
      - "v*.*.*"

jobs: 
  BuildPackage:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
        
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
          
      - name: "Run maven package"
        run: mvn -DskipTests package

      - run: ls -la target/

      - run: mv target/*.jar target/app.jar

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/app.jar"
          body: "My release ${{ github.ref }}"
          name: "Release candidate ${{ github.ref }}"
      
